### ISSUE TITLE
mapbox-file-type reporting "Unknown filetype" on well-formed geojson

### ISSUE THREAD

**Issue by jacquestardie** [mapbox/mapbox-file-sniff#35] opened 2016-02-02 02:09 UTC
@jakepruitt helped me track down an issue with `mapbox-file-type`, which when installed locally, was outputting the following:

```
❯ mapbox-file-type file.geojson
Unknown filetype
```

This geojson was known to work with geojson.io — but would fail when attempting to upload to Mapbox Studio.

After taking a look at the `geojson`, we noticed that `"type": "FeatureCollection"` had been appended to the bottom of the file. Usually that's seen first.

```bash
          ]
        ],
        "type": "Polygon"
      },
      "properties": {},
      "type": "Feature"
    }
  ],
  "type": "FeatureCollection"
}
```

After rearranging `"type": "FeatureCollection"` to the top of the file, we get:

```bash
❯ mapbox-file-type dg_metro_pretty.geojson
geojson
```

After which, the upload to Mapbox Studio went through successfully.

Not sure what the next actions here would be, but thought I'd report in case this was unexpected/unwanted behavior.

**Comment by rclark** [comment] 2016-02-03 16:12
This problem boils down to the fact that there's not any meaningful way to detect a geojson file without parsing the entire file. Keep in mind that this library needs to differentiate data files ranging from tiny CSV files to 20+ GB tiffs, where the entire file cannot be loaded into memory.

In my opinion the best option here is to document that in order for geojson to be detected, we need `type` at the beginning of the file.

**Comment by perrygeo** [comment] 2016-02-03 19:52
Enforcing a particular key order would mean rejecting valid GeoJSON since the order is not defined in the JSON spec

> 4.3.3 Object
> An object is a member of the type Object. It is an **unordered** collection of properties each of which
> contains a primitive value, object, or function. A function stored in a property of an object is called a
> method.

There's got to be a more robust way to detect GeoJSON that doesn't reject valid data but stays reasonably fast. It looks pretty bad if the output of some of our own tools can't be loaded into Studio.

What about looking for top-level `features` property whose value is an `array`? Or detecting that the file is text and starts with a `{` and sending it to [geojsonhint](https://github.com/mapbox/geojsonhint)? Or reading a few lines up from the bottom of the file?

**Comment by sgillies** [comment] 2016-02-03 20:56
@rclark @perrygeo Detecting GeoJSON without adding any draconian constraints to data (JSON objects are unordered and GeoJSON is no different) should be pretty easy.

According to the project's readme, there are two JSON formats to be detected: [TileJSON](https://github.com/mapbox/tilejson-spec) and [GeoJSON](https://github.com/geojson/draft-geojson). If the uploaded file starts with (see https://tools.ietf.org/html/rfc7159#section-2)

`      begin-object    = ws %x7B ws  ; { left curly bracket`

then it's JSON, Tile- or Geo-flavored. In this case, do a fast check for TileJSON-ness – TileJSON docs are small (100s of bytes) – and assume GeoJSON otherwise. How does that sound?

**Comment by rclark** [comment] 2016-02-03 21:03
We have systems that utilize this library and only have access to the first 512 bytes of a file. 

I'm starting to lean in a direction where we drop any notion in this repo that we can differentiate JSON from GeoJSON from TopoJSON with that constraint. It can guess that this is JSON, and allow the data through, to be rejected later by https://github.com/mapbox/mapbox-upload-validate when the entre file's content is accessible.

cc @GretaCB

**Comment by danswick** [comment] 2016-03-28 23:56
This issue came up again today on a help request where `"type": "FeatureCollection"` followed `"features": []` in the user's GeoJSON. Moving `"type": "FeatureCollection"` to the beginning resolved the issue as expected.

**Comment by who8mycakes** [comment] 2016-08-23 17:15
Picking up on this, I was unable to replicate the `Unknown filetype` error. If this issue comes up again for anyone, please include a GeoJSON testcase for investigation.

**Comment by mapsam** [comment] 2016-08-25 19:10
I think this issue is caused by a geojson with two specific quirks:

1. The `"type": "FeatureCollection"` is at the end of the JSON, as originally discussed
1. The first `Feature` in the collection has `"type"` after a very large `geometry` AND/OR large `properties` section.

If the `type: FeatureCollection` is at the end, it's likely the first `"type"` to be found by the string parser is going to to be the `type` of the first `Feature` in the array, which in that case would lead to the file being detected as a geojson regardless. So, the only way files are failing like this is if they match number `2` above as well. Here's a fake fixture with a property `"nam"` that is super long, and cuts off the rest of the feature:

```JSON
{
  "features": [
    {
      "properties": {
        "name": "Phasellus nec bibendum lacus. Nullam sit amet leo ipsum. Aliquam erat volutpat. Morbi sollicitudin risus at tristique gravida. Duis ornare ullamcorper arcu ut malesuada. Ut sapien massa, aliquet lobortis iaculis sed, venenatis eget ante. Sed aliquet nunc nunc, sit amet tincidunt libero aliquet nec. Curabitur nec dui ut ex blandit sagittis id at augue. Suspendisse et metus eget lorem lacinia congue. Aenean dictum finibus condimentum. Donec ultricies convallis orci, sit amet sodales orci gravida id. Nam sagittis neque vel congue maximus. Mauris porta quam non hendrerit consectetur. Aliquam congue nibh at nisl pulvinar varius. Nunc in ullamcorper tellus. Sed hendrerit metus metus, quis tincidunt felis consectetur eu."
      },
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [125.6, 10.1]
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [125.6, 10.1]
      },
      "properties": {
        "name": "Dinagat Islands"
      }
    }
  ],
  "type": "FeatureCollection"
}
```

Here's the resulting header that we run the checks on:

```
{
"features":[
{
"properties":{
"name":"Phasellusnecbibendumlacus.Nullamsitametleoipsum.Aliquameratvolutpat.Morbisollicitudinrisusattristiquegravida.Duisornareullamcorperarcuutmalesuada.Utsapienmassa,aliquetlobortisiaculissed,venenatisegetante.Sedaliquetnuncnunc,sitamettinciduntliberoaliquetnec.Curabiturnecduiutexblanditsagit
```

cc @who8mycakes @rclark @GretaCB

**Comment by who8mycakes** [comment] 2016-08-31 16:38
Capturing from chat with @GretaCB, we noted that in addition to `type:` plus a member value, a `crs` or `bbox` member also is an [indicator of GeoJSON file type](http://geojson.org/geojson-spec.html#geojson-objects).

In approaching this issue, I'm going to:
- [ ] Look through the GeoJSON style spec to see if there are any other additional object members or parameters that could be GeoJSON indicators
- [ ] Create invalid and valid GeoJSON test fixtures to test
- [ ] Write tests to run the fixtures against
- [ ] When tests are 🍏 , start tinkering with the argument logic to include the add'l parameters for GeoJSON validation

@GretaCB Please drop any edits, additions, or notes to the above plan.

**Comment by GretaCB** [comment] 2016-08-31 20:54
@who8mycakes this looks 👍 . 

> When tests are 🍏

The tests will likely be failing once you add your new tests and fixtures. The would then be to get them to pass 🍏

**Comment by sgillies** [comment] 2016-09-01 08:49
@who8mycakes please see https://github.com/mapbox/hey/issues/5211 too. I've got a solid suggestion there for how to detect GeoJSON texts and objects: "features", "geometry", and "coordinates" are the primary keys to look for, not "crs" or "bbox".

GeoJSON and JSON items are not particularly ordered and we can't require or expect "type" to come first.

**Comment by GretaCB** [comment] 2016-09-01 13:26
Ooooo, this is a great post @sgillies. 

Curious what your thoughts are on [this user's geojson file](https://github.com/mapbox/mapbox-file-sniff/issues/44). Are you suggesting to disregard `crs` and `bbox` properties if they are the first properties in the object, and to continue searching for the other primary properties (features, geometry, coordinates), which perhaps hold more validation weight?

**Comment by sgillies** [comment] 2016-09-01 15:52
Right. The GeoJSON RFC says 'don't use "crs"' and it'll be less used and a less useful indicator of GeoJSON as time goes on. "bbox" is a recommendation, not a requirement, and is not very common. "features" is a requirement of a FeatureCollection; it's gotta be there and it has to (because of JSON grammar) precede the bulk of the feature collection text.

**Comment by who8mycakes** [comment] 2016-09-06 19:50
@sgillies Thanks for adding clarification here. I've added `features`, `geometries`, and `coordinates` as detection parameters, and will be adding a tag for these changes. Can I get your 👍  or 👎  before I move ahead with tagging?

**Comment by mapsam** [comment] 2016-09-06 20:19
Nice, good call @sgillies! Thanks for implementing @who8mycakes.

**Comment by GretaCB** [comment] 2016-09-29 16:55
Fix deployed to production per https://github.com/mapbox/mapbox-file-sniff/pull/45. Closing.

**Closed by GretaCB** 2016-09-29 16:55 UTC
Labels: bug
